//
//  NewsAPIEnums.swift
//  NewsApp
//
//  Created by Vladimir Yanakiev on 17.02.22.
//

import Foundation

enum NewsCategory: String {
    case business = "business"
    case entertainment = "entertainment"
    case general = "general"
    case health = "health"
    case science = "science"
    case sports = "sports"
    case technology = "technology"
}

enum NewsCountry: String {
    case ae = "ae"
    case ar = "ar"
    case at = "at"
    case au = "au"
    case be = "be"
    case bg = "bg"
    case br = "br"
    case ca = "ca"
    case ch = "ch"
    case cn = "cn"
    case co = "co"
    case cu = "cu"
    case cz = "cz"
    case de = "de"
    case eg = "eg"
    case fr = "fr"
    case gb = "gb"
    case gr = "gr"
    case hk = "hk"
    case hu = "hu"
    case id = "id"
    case ie = "ie"
    case il = "il"
    case `in` = "in"
    case it = "it"
    case jp = "jp"
    case kr = "kr"
    case lt = "lt"
    case lv = "lv"
    case ma = "ma"
    case mx = "mx"
    case my = "my"
    case ng = "ng"
    case nl = "nl"
    case no = "no"
    case nz = "nz"
    case ph = "ph"
    case pl = "pl"
    case pt = "pt"
    case ro = "ro"
    case rs = "rs"
    case ru = "ru"
    case sa = "sa"
    case se = "se"
    case sg = "sg"
    case si = "si"
    case sk = "sk"
    case th = "th"
    case tr = "tr"
    case tw = "tw"
    case ua = "ua"
    case us = "us"
    case ve = "ve"
    case za = "za"
}

enum NewsSource: String {
    case AustralianBroadcastCorporation = "abc-news-au"
    case ArsTechnica = "ars-technica"
    case AP = "associated-press"
    case BBC = "bbc-news"
    case BBCSport = "bbc-sport"
    case Bild = "bild"
    case Bloomberg = "bloomberg"
    case BusinessInsider = "business-insider"
    case BusinessInsiderUK = "business-insider-uk"
    case BuzzFeed = "buzzfeed"
    case CNBC = "cnbc"
    case CNN = "cnn"
    case DailyMail = "daily-mail"
    case Engadget = "engadget"
    case EntertainmentWeekly = "entertainment-weekly"
    case ESPN = "espn"
    case ESPNCricInfo = "espn-cric-info"
    case FinancialTimes = "financial-times"
    case Focus = "focus"
    case FootballItalia = "football-italia"
    case Fortune = "fortune"
    case FourFourTwo = "four-four-two"
    case FoxSports = "fox-sports"
    case Google = "google-news"
    case GruenderSzene = "gruender-szene"
    case HackerNews = "hacker-news"
    case IGN = "ign"
    case Independent = "independent"
    case Mashable = "mashable"
    case Metro = "metro"
    case Mirror = "mirror"
    case MTVNews = "mtv-news"
    case MTVNewsUK = "mtv-news-uk"
    case NatGeo = "national-geographic"
    case NewScientist = "new-scientist"
    case NewsWeek = "newsweek"
    case NewYorkMagazine = "new-york-magazine"
    case NFLNews = "nfl-news"
    case Polygon = "polygon"
    case Recode = "recode"
    case Reddit = "reddit-r-all"
    case Reuters = "reuters"
    case SkyNews = "sky-news"
    case SkySportsNews = "sky-sports-news"
    case SpiegelOnline = "spiegel-online"
    case t3n = "t3n"
    case TalkSport = "talksport"
    case TechCrunch = "techcrunch"
    case TechRadar = "techradar"
    case TheEconomist = "the-economist"
    case TheGuardianAU = "the-guardian-au"
    case TheGuardianUK = "the-guardian-uk"
    case TheHindu = "the-hindu"
    case HuffPo = "the-huffington-post"
    case TheLadBible = "the-lad-bible"
    case NTY = "the-new-york-times"
    case TNW = "the-next-web"
    case TheSportBible = "the-sport-bible"
    case TheTelegraph = "the-telegraph"
    case TheTimesOfIndia = "the-times-of-india"
    case TheVerge = "the-verge"
    case WSJ = "the-wall-street-journal"
    case TheWatshingtonPost = "the-washington-post"
    case Time = "timet"
    case USA = "usa-today"
    case Wired = "wired-de"

}
